# Generated by Django 5.0.7 on 2024-09-14 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enroller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('pincode', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('adhar_card', models.FileField(upload_to='')),
                ('pan_card', models.FileField(upload_to='')),
                ('loan_amount', models.IntegerField()),
                ('tenure', models.IntegerField()),
                ('intrest_rate', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
    ]
