# Generated by Django 5.0.7 on 2024-09-17 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enroller',
            name='adhar_card',
            field=models.FileField(upload_to='calculator/upload_file/adhar/'),
        ),
        migrations.AlterField(
            model_name='enroller',
            name='pan_card',
            field=models.FileField(upload_to='calculator/upload_file/pan'),
        ),
    ]
