# Generated by Django 5.0.7 on 2024-09-18 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_alter_enroller_adhar_card_alter_enroller_pan_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='enroller',
            name='city',
            field=models.TextField(default='Chandigarh', max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='enroller',
            name='country',
            field=models.CharField(default='India', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='enroller',
            name='post_office_name',
            field=models.CharField(default='No Office', max_length=350, null=True),
        ),
    ]
